name: Continuous Integration

on: [push, pull_request]

jobs:
  watcom_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install dosbox dos2unix
    - name: build
      timeout-minutes: 20
      run: |
        ./build/build.sh rel
    - name: Find Git version
      id: version
      run: |
        if git describe --exact-match --tags >/dev/null; then
          VERSION=$(git describe --exact-match --tags)
          VERSION=${VERSION/#imaginot-/}
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload EXEs
      uses: actions/upload-artifact@v1
      with:
        path: "rel"
        name: imaginot-${{steps.version.outputs.VERSION}}
